fix CI

diff --git a/.github/workflows/destroy-infrastructure.yaml b/.github/workflows/destroy-infrastructure.yaml
--- a/.github/workflows/destroy-infrastructure.yaml
+++ b/.github/workflows/destroy-infrastructure.yaml
@@ -59,3 +59,66 @@ jobs:
 
       - name: Apply Terraform plan
         run: terraform apply tfplan -destroy
+
+  destroy-main-infrastructure:
+    runs-on: self-hosted
+    environment: ${{ inputs.environment }}
+
+    outputs:
+      resource_group_name: ${{ steps.generate-outputs.outputs.resource_group_name }}
+      functionapp_name: ${{ steps.generate-outputs.outputs.functionapp_name }}
+
+    defaults:
+      run:
+        working-directory: src/infrastructure
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Verify Inputs
+        run: |
+          allowed_environments=("dev" "prod")
+          if [[ ! " ${allowed_environments[@]} " =~ " ${{ inputs.environment }} " ]]; then
+            echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: ${allowed_environments[@]}"
+            exit 1
+          fi
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_wrapper: false
+
+      - name: Terraform Init
+        env:
+          # backend configuration
+          AZ_TERRAFORM_BACKEND_STORAGEACCOUNT: ${{ vars.AZ_TERRAFORM_BACKEND_STORAGEACCOUNT }}
+          AZ_TERRAFORM_BACKEND_RESOURCEGROUP: ${{ vars.AZ_TERRAFORM_BACKEND_RESOURCEGROUP }}
+          AZ_BACKEND_CONTAINER_NAME: ${{ inputs.environment }}
+          AZ_MAIN_STATE_FILE_KEY: "main.terraform.tfstate"
+        run: |
+          terraform init \
+            -backend-config="storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}"  \
+            -backend-config="container_name=${AZ_BACKEND_CONTAINER_NAME}" \
+            -backend-config="key=${AZ_MAIN_STATE_FILE_KEY}" \
+            -backend-config="resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
+
+      - name: Terraform Plan
+        env:
+          AZ_OWNER_OBJECT_ID: ${{ secrets.AZ_OWNER_OBJECT_ID }}
+          AZ_OPENAI_STATE_FILE_KEY: "openai.terraform.tfstate"
+          AZ_BACKEND_CONTAINER_NAME: ${{ inputs.environment }}
+          AZ_TERRAFORM_BACKEND_STORAGEACCOUNT: ${{ vars.AZ_TERRAFORM_BACKEND_STORAGEACCOUNT }}
+          AZ_TERRAFORM_BACKEND_RESOURCEGROUP: ${{ vars.AZ_TERRAFORM_BACKEND_RESOURCEGROUP }}
+        run: |
+          terraform plan -destroy -out=tfplan -var-file=environments/${{ inputs.environment }}.tfvars \
+            -var="application_owner_object_id=${AZ_OWNER_OBJECT_ID}" \
+            -var="openai_state_storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}" \
+            -var="openai_state_container_name=${AZ_BACKEND_CONTAINER_NAME}" \
+            -var="openai_state_resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
+            -var="openai_state_key=${AZ_OPENAI_STATE_FILE_KEY}" \
+            -var="telegram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
+            -var="telegram_bot_secret_header=${{ secrets.TELEGRAM_BOT_SECRET_HEADER }}"
+
+      - name: Apply Terraform plan
+        run: terraform apply tfplan -destroy
